name: labonne_sante
description: "An ecommerce app for pharmatacy products called la bonne sante"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  drift: ^2.28.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod: ^3.0.3
  sqlite3_flutter_libs: ^0.5.40


dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mockito: ^5.5.0


flutter:
  uses-material-design: true
